### ISSUE TITLE
!wikipedia computer breaks because of ascii codec issue

### ISSUE THREAD

**Issue by kilbyjmichael** [kilbyjmichael/BabyPyIRC#2]
Traceback (most recent call last):
  File "C:\Users\mkilby\Downloads\BabyPyIRC-master\BabyPyIRC-master\PyBot.py", line 16, in <module>
    irc.test_data(data, CHAN)
  File "C:\Users\mkilby\Downloads\BabyPyIRC-master\BabyPyIRC-master\irc.py", line 41, in test_data
    wiki_return = str(wikipedia.summary(com_args))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 1488: ordinal not in range(128)

**Comment by kilbyjmichael** [comment]
!wikipedia x (space) x breaks because of the ascii issue too
